# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               Bristol MaVi
usename4navbar:     False   #Allows for a different name to be used in the navigation bar (see navbar.html)
title:              "Bristol Machine Learning & Computer Vision"
description:        "We aim to further our understanding of brain functioning via computational and mathematical modelling."


# URL
url:                https://uob-mavi.github.io/people
#baseurl:            https://uob-mavi.github.io/people
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "PEOPLE"
    href:           "/people"
  - name:           "MEETINGS"
    href:           "/meetings"    
  - name:           "NEWS"
    href:           "/news"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
